name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
    - name: Lint with flake8
      run: |
        pipenv install flake8
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=C,E,F,W,B,B950 --ignore=E203,E501,W503 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=13 --max-line-length=100 --statistics
     - name: Test with pytest
       run: |
         pipenv install pytest
         pipenv run pytest